### ISSUE TITLE
NulllReferenceException spam when Little Disciple is held

### ISSUE THREAD

**Issue by lostdoge08** [prodzpod/MysticsRisky2Utils#1]
This error is being spammed in the console after I (believably) picked up Little Disciple. Not 100% sure, but its seems to have started around the time I picked it up, and the item itself is bugged out and the wisps don't move (except for very occasionally). Also could be an unrelated mod causing issues but thought I would post this to be safe.

![Screenshot_76](https://github.com/user-attachments/assets/aa30e530-2f0a-4252-931d-beca1bcf9189)

![imaadssdage](https://github.com/user-attachments/assets/764c09de-0034-4507-903e-3bc06a021747)

**Comment by prodzpod** [comment]
should be fixed ???? feel free to reopen if issue persist
